ASPCore/Controllers/BillingController.cs
using FireSharp;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.BillingPortal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Task6_ANDRE.Models;

namespace Task6_ANDRE.Controllers
{
    public class BillingController : Controller
    {
        // GET: Billing/Create
        public ActionResult ManageBilling()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ManageBilling(FormCollection collection)
        {
            try
            {
                StripeConfiguration.ApiKey = "sk_test_51GtwelDUISIWU8NfIfToFjnvtQ3h4paJJ8JtyyXoivVWYrBZJlFqT3hQolgzBJcLe2VeoiugMfgx3LmZuKeNCrkh004UHd1BPs";

                var options = new SessionCreateOptions
                {
                    Customer = "cus_HWcnIFFtqiH3TB",
                    ReturnUrl = "https://billing.stripe.com/session/{SESSION_SECRET}",
                };
                var service = new SessionService();
                service.Create(options);

                return Redirect(options.ReturnUrl);
            }
            catch
            {
                return View();
            }
        }
    }
}

ASPCore/Controllers/CartController.cs
using FireSharp;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Task6_ANDRE.Models;

namespace Task6_ANDRE.Controllers
{
    public class CartController : Controller
    {
        

        

        // GET: Cart/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cart/Create
        [HttpPost]
        public ActionResult Create(ChargeDTO chargeDto,ChargeViewModel chargeViewModel)
        {
            try
            {
                StripeConfiguration.ApiKey = "sk_test_51GtwelDUISIWU8NfIfToFjnvtQ3h4paJJ8JtyyXoivVWYrBZJlFqT3hQolgzBJcLe2VeoiugMfgx3LmZuKeNCrkh004UHd1BPs";

                var eventService = new EventService();
                //eventService.Get();

                // `source` is obtained with Stripe.js; see https://stripe.com/docs/payments/accept-a-payment-charges#web-create-token

                var customerOptions = new CustomerCreateOptions
                {
                    Description = chargeDto.CardName,
                    Source = chargeDto.StripeToken,
                    Email = chargeDto.Email,
                    Metadata = new Dictionary<string, string>()
                    {
                        {"Phone Number", chargeDto.Phone }
                    }
                };
                var customerService = new CustomerService();
                Customer customer = customerService.Create(customerOptions);

                var subscriptionOptions = new SubscriptionCreateOptions
                {
                    Customer = customer.Id,
                    Items = new List<SubscriptionItemOptions>
                    {
                        new SubscriptionItemOptions
                        {
                            Price = "price_1GuKOsDUISIWU8NftyytS3Qc",
                        },
                    },
                };

                var service = new SubscriptionService();
                Subscription charge = service.Create(subscriptionOptions);

                

                var model = new ChargeViewModel();
                model.customerName = Convert.ToString(charge.Customer);
                model.PriceId = string.Format("{0:#.00}", Convert.ToDecimal(charge.Plan.Amount) / 100);
                

                return View("OrderStatus", model);
            }
            catch
            {
                return View();
            }
        }
    }
}

ASPCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Stripe", "Create", "Cart")</li>
                    <li>@Html.ActionLink("Manage Billing", "ManageBilling", "Billing")</li>
                    <li>@Html.ActionLink("Refund", "Refund")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
    @RenderSection("stripe", required: false)
    @RenderSection("managebilling", required: false)
    @RenderSection("refund", required: false)
</body>
</html>